server.port=8045
image.url=http://192.168.2.182:8045/v1/img-api

# MySQL Database connection
#spring.datasource.url=jdbc:mysql://mac:3306/scan?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:sqlite:/Users/weepwood/Developer/scan.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Enable SQL logging
logging.level.com.zjcxph.imgapi.mapper=DEBUG

logging.level.root=INFO
logging.file.name=img-api.log
logging.logback.rollingpolicy.max-file-size=10MB

# MyBatis configuration
#mybatis.mapper-locations=classpath:mapper/*.xml
#mybatis.type-aliases-package=com.zjcxph.imgapi.entity

image.username=br_admin
image.password=br_password
image.basePath=/Users/weepwood/Developer/TOMAC/temp/FTP/scan

# application.properties
spring.devtools.restart.enabled=true
management.endpoints.web.exposure.include=health,info