-- ============================================================
-- MRR Database Schema (PostgreSQL, schema=app)
-- 完整建表入口，包含所有表结构、索引、视图、函数和种子数据
-- ============================================================

CREATE SCHEMA IF NOT EXISTS app;

CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

-- ============================================
-- 1. 核心业务表
-- ============================================

-- 1.1 扫描记录（含 OSS 迁移字段）
CREATE TABLE IF NOT EXISTS app.mr_scan (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brxh             TEXT,
    bah              TEXT,
    sjh              TEXT,
    filename         TEXT,
    btype            INTEGER,
    pages            INTEGER,
    openerno         TEXT,
    uploaddate       TEXT,
    uploadflag       INTEGER,
    folder           TEXT,
    oss_url          TEXT,
    file_size        BIGINT,
    checksum_md5     VARCHAR(32),
    migration_status VARCHAR(20) DEFAULT 'not_migrated',
    migrated_at      TIMESTAMP WITHOUT TIME ZONE
);

COMMENT ON TABLE  app.mr_scan IS '扫描记录 — 核心业务表';
COMMENT ON COLUMN app.mr_scan.oss_url          IS 'OSS 对象 key';
COMMENT ON COLUMN app.mr_scan.file_size        IS '文件大小（字节）';
COMMENT ON COLUMN app.mr_scan.checksum_md5     IS 'MD5 校验值';
COMMENT ON COLUMN app.mr_scan.migration_status IS '迁移状态: not_migrated/migrated/verified';
COMMENT ON COLUMN app.mr_scan.migrated_at      IS '迁移完成时间';

-- 1.2 患者信息
CREATE TABLE IF NOT EXISTS app.mr_patient (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcard        TEXT,
    bah           TEXT,
    admissiontime TEXT,
    department    TEXT,
    name          TEXT
);

COMMENT ON TABLE app.mr_patient IS '患者信息';

-- 1.3 统计数据
CREATE TABLE IF NOT EXISTS app.mr_statistics (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bah      TEXT,
    cid      TEXT,
    openerno TEXT,
    date     TEXT,
    type     TEXT,
    pages    INTEGER,
    sjh      TEXT
);

COMMENT ON TABLE app.mr_statistics IS '统计数据';

-- ============================================
-- 2. 认证授权表
-- ============================================

-- 2.1 角色
CREATE TABLE IF NOT EXISTS app.mr_auth_role (
    code        TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    permissions TEXT NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0
);

COMMENT ON TABLE app.mr_auth_role IS '认证角色';

-- 2.2 用户
CREATE TABLE IF NOT EXISTS app.mr_auth_user (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    display_name  TEXT,
    password_hash TEXT NOT NULL,
    role_code     TEXT NOT NULL REFERENCES app.mr_auth_role (code) ON UPDATE CASCADE,
    status        TEXT NOT NULL DEFAULT 'active',
    last_login_at TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE app.mr_auth_user IS '认证用户';

-- ============================================
-- 3. 运维表
-- ============================================

-- 3.1 访问日志
CREATE TABLE IF NOT EXISTS app.access_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT,
    client_ip       TEXT,
    request_uri     TEXT,
    method          TEXT,
    user_agent      TEXT,
    access_time     TIMESTAMP WITHOUT TIME ZONE,
    query_string    TEXT,
    request_body    TEXT,
    response_status TEXT,
    execute_time    BIGINT,
    referer         TEXT,
    audit_action    TEXT,
    audit_target    TEXT,
    audit_description TEXT
);

COMMENT ON TABLE app.access_log IS '访问日志';
COMMENT ON COLUMN app.access_log.audit_action      IS '审计动作类型: LIST/DOWNLOAD/VIEW_IMAGE/VIEW_OSS_IMAGE';
COMMENT ON COLUMN app.access_log.audit_target      IS '审计目标（病案号/图片ID）';
COMMENT ON COLUMN app.access_log.audit_description IS '审计描述';

-- 3.2 图片迁移日志
CREATE TABLE IF NOT EXISTS app.image_migration_log (
    id               BIGSERIAL PRIMARY KEY,
    scan_id          INTEGER NOT NULL REFERENCES app.mr_scan (id) ON DELETE CASCADE,
    local_path       TEXT NOT NULL,
    oss_url          TEXT,
    migration_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    error_message    TEXT,
    file_size        BIGINT,
    checksum_md5     VARCHAR(32),
    migrated_at      TIMESTAMP WITHOUT TIME ZONE,
    verified_at      TIMESTAMP WITHOUT TIME ZONE,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  app.image_migration_log IS '图片迁移日志表 — 追踪每张图片的迁移状态';
COMMENT ON COLUMN app.image_migration_log.scan_id          IS '关联的扫描记录ID';
COMMENT ON COLUMN app.image_migration_log.local_path       IS '本地文件路径';
COMMENT ON COLUMN app.image_migration_log.oss_url          IS 'OSS 文件URL (object key)';
COMMENT ON COLUMN app.image_migration_log.migration_status IS '迁移状态: pending/migrating/success/failed/verified/rollback';
COMMENT ON COLUMN app.image_migration_log.error_message    IS '错误信息（失败时）';
COMMENT ON COLUMN app.image_migration_log.file_size        IS '文件大小（字节）';
COMMENT ON COLUMN app.image_migration_log.checksum_md5     IS '文件MD5校验值';
COMMENT ON COLUMN app.image_migration_log.migrated_at      IS '迁移完成时间';
COMMENT ON COLUMN app.image_migration_log.verified_at      IS '验证完成时间';

-- 3.3 迁移任务
CREATE TABLE IF NOT EXISTS app.migration_job (
    id              BIGSERIAL PRIMARY KEY,
    status          VARCHAR(20)   NOT NULL DEFAULT 'pending',
    total_count     BIGINT        NOT NULL DEFAULT 0,
    processed_count BIGINT        NOT NULL DEFAULT 0,
    failed_count    BIGINT        NOT NULL DEFAULT 0,
    rate            NUMERIC(5,2)  DEFAULT 0,
    error_message   TEXT,
    created_by      TEXT,
    started_at      TIMESTAMP WITHOUT TIME ZONE,
    completed_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  app.migration_job IS 'OSS 迁移任务表 — 追踪批量迁移任务执行状态';
COMMENT ON COLUMN app.migration_job.status          IS '任务状态: pending/running/completed/failed/cancelled';
COMMENT ON COLUMN app.migration_job.total_count     IS '待迁移文件总数';
COMMENT ON COLUMN app.migration_job.processed_count IS '已处理文件数';
COMMENT ON COLUMN app.migration_job.failed_count    IS '失败文件数';
COMMENT ON COLUMN app.migration_job.rate            IS '完成百分比';
COMMENT ON COLUMN app.migration_job.created_by      IS '任务创建者（用户名）';

-- 3.9 系统设置表
CREATE TABLE IF NOT EXISTS app.mr_system_settings (
    id              SERIAL PRIMARY KEY,
    setting_key     VARCHAR(128) NOT NULL UNIQUE,
    setting_value   TEXT,
    description     VARCHAR(512),
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_by      VARCHAR(64)
);

COMMENT ON TABLE  app.mr_system_settings             IS '系统设置表 — 键值对存储系统级配置';
COMMENT ON COLUMN app.mr_system_settings.setting_key  IS '设置键（唯一）';
COMMENT ON COLUMN app.mr_system_settings.setting_value IS '设置值';
COMMENT ON COLUMN app.mr_system_settings.description  IS '设置项说明';
COMMENT ON COLUMN app.mr_system_settings.updated_by   IS '最后修改用户';

-- ============================================
-- 4. 索引
-- ============================================

-- 4.1 mr_scan 索引
CREATE INDEX IF NOT EXISTS idx_mr_scan_bah               ON app.mr_scan (bah);
CREATE INDEX IF NOT EXISTS idx_mr_scan_brxh              ON app.mr_scan (brxh);
CREATE INDEX IF NOT EXISTS idx_mr_scan_sjh               ON app.mr_scan (sjh);
CREATE INDEX IF NOT EXISTS idx_mr_scan_folder_id          ON app.mr_scan (folder, id);
CREATE INDEX IF NOT EXISTS idx_mr_scan_migration_status   ON app.mr_scan (migration_status);
CREATE INDEX IF NOT EXISTS idx_mr_scan_oss_url            ON app.mr_scan (oss_url) WHERE oss_url IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mr_scan_pending_id         ON app.mr_scan (id) WHERE uploadflag != 0 AND (oss_url IS NULL OR oss_url = '');
CREATE INDEX IF NOT EXISTS idx_mr_scan_pending_folder_id  ON app.mr_scan (folder, id) WHERE uploadflag != 0 AND (oss_url IS NULL OR oss_url = '');
CREATE INDEX IF NOT EXISTS idx_mr_scan_bah_cover          ON app.mr_scan (bah) INCLUDE (filename, pages, btype);

-- 4.2 mr_statistics 索引
CREATE INDEX IF NOT EXISTS idx_mr_statistics_bah  ON app.mr_statistics (bah);
CREATE INDEX IF NOT EXISTS idx_mr_statistics_date ON app.mr_statistics (date);
CREATE INDEX IF NOT EXISTS idx_mr_statistics_date_normalized ON app.mr_statistics ((replace(date, '/', '-')));
CREATE INDEX IF NOT EXISTS idx_mr_statistics_keyword_trgm ON app.mr_statistics USING gin ((coalesce(cid, '') || chr(1) || coalesce(openerno, '') || chr(1) || coalesce(date, '') || chr(1) || coalesce(type, '')) public.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_mr_statistics_type ON app.mr_statistics (type);
CREATE INDEX IF NOT EXISTS idx_mr_statistics_sjh  ON app.mr_statistics (sjh);

-- 4.3 mr_patient 索引
CREATE INDEX IF NOT EXISTS idx_mr_patient_idcard ON app.mr_patient (idcard);
CREATE INDEX IF NOT EXISTS idx_mr_patient_bah     ON app.mr_patient (bah);

-- 4.4 mr_auth_user 索引（username 的 UNIQUE 约束已自动创建索引）
CREATE INDEX IF NOT EXISTS idx_mr_auth_user_role_code ON app.mr_auth_user (role_code);

-- 4.5 access_log 索引（BRIN 适用于大容量追加型日志表）
CREATE INDEX IF NOT EXISTS idx_access_log_access_time      ON app.access_log USING BRIN (access_time) WITH (pages_per_range = 32);
CREATE INDEX IF NOT EXISTS idx_access_log_access_time_id   ON app.access_log (access_time ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_access_log_client_ip        ON app.access_log (client_ip);
CREATE INDEX IF NOT EXISTS idx_access_log_request_uri      ON app.access_log (request_uri);
CREATE INDEX IF NOT EXISTS idx_access_log_method           ON app.access_log (method);
CREATE INDEX IF NOT EXISTS idx_access_log_response_status  ON app.access_log (response_status);
CREATE INDEX IF NOT EXISTS idx_access_log_method_status    ON app.access_log (method, response_status);
CREATE INDEX IF NOT EXISTS idx_access_log_keyword_common_trgm ON app.access_log USING gin ((coalesce(username, '') || chr(1) || coalesce(client_ip, '') || chr(1) || coalesce(request_uri, '') || chr(1) || coalesce(query_string, '') || chr(1) || coalesce(user_agent, '')) public.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_access_log_referer_trgm     ON app.access_log USING gin (referer public.gin_trgm_ops);

-- 4.6 image_migration_log 索引
CREATE INDEX IF NOT EXISTS idx_migration_status         ON app.image_migration_log (migration_status);
CREATE INDEX IF NOT EXISTS idx_migration_scan_id        ON app.image_migration_log (scan_id);
CREATE INDEX IF NOT EXISTS idx_migration_created_at     ON app.image_migration_log (created_at);
CREATE INDEX IF NOT EXISTS idx_migration_status_created ON app.image_migration_log (migration_status, created_at);
CREATE INDEX IF NOT EXISTS idx_migration_scan_created   ON app.image_migration_log (scan_id, created_at DESC);

-- 4.7 migration_job 索引
CREATE INDEX IF NOT EXISTS idx_migration_job_status     ON app.migration_job (status);
CREATE INDEX IF NOT EXISTS idx_migration_job_created_at ON app.migration_job (created_at DESC);

-- ============================================
-- 5. 视图
-- ============================================

-- 5.1 迁移状态统计
CREATE OR REPLACE VIEW app.v_migration_statistics AS
SELECT
    migration_status,
    COUNT(*) AS count,
    ROUND(COUNT(*) * 100.0 / NULLIF(SUM(COUNT(*)) OVER (), 0), 2) AS percentage
FROM app.image_migration_log
GROUP BY migration_status;

COMMENT ON VIEW app.v_migration_statistics IS '迁移状态统计视图';

-- 5.2 待迁移图片列表
CREATE OR REPLACE VIEW app.v_pending_migrations AS
SELECT
    s.id   AS scan_id,
    s.bah,
    s.brxh,
    s.filename,
    s.folder,
    CONCAT('./data/img/', LEFT(s.folder, 5), '/', s.folder, '/', s.brxh, '-', s.bah, '/', s.filename) AS local_path,
    s.oss_url,
    s.migration_status
FROM app.mr_scan s
WHERE s.uploadflag != 0
  AND (s.oss_url IS NULL OR s.oss_url = '')
ORDER BY s.id;

COMMENT ON VIEW app.v_pending_migrations IS '待迁移图片列表视图';

-- ============================================
-- 6. 函数
-- ============================================

-- 6.1 初始化迁移日志
CREATE OR REPLACE FUNCTION app.init_migration_logs()
RETURNS VOID AS $$
DECLARE
    rec RECORD;
    inserted INT := 0;
BEGIN
    FOR rec IN
        SELECT id, bah, brxh, filename, folder
        FROM app.mr_scan
        WHERE uploadflag != 0
          AND (oss_url IS NULL OR oss_url = '')
          AND id NOT IN (SELECT scan_id FROM app.image_migration_log)
    LOOP
        INSERT INTO app.image_migration_log (scan_id, local_path, migration_status)
        VALUES (
            rec.id,
            CONCAT('./data/img/', LEFT(rec.folder, 5), '/', rec.folder, '/', rec.brxh, '-', rec.bah, '/', rec.filename),
            'pending'
        );
        inserted := inserted + 1;
    END LOOP;
    RAISE NOTICE 'Migration logs initialized: % records', inserted;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION app.init_migration_logs() IS '初始化迁移日志 — 为所有待迁移图片创建日志记录';

-- 6.2 更新迁移状态
CREATE OR REPLACE FUNCTION app.update_migration_status(
    p_scan_id       INTEGER,
    p_status        VARCHAR(20),
    p_oss_url       TEXT DEFAULT NULL,
    p_error_message TEXT DEFAULT NULL,
    p_checksum_md5  VARCHAR(32) DEFAULT NULL,
    p_file_size     BIGINT DEFAULT NULL
) RETURNS VOID AS $$
BEGIN
    UPDATE app.image_migration_log
    SET
        migration_status = p_status,
        oss_url          = COALESCE(p_oss_url, oss_url),
        error_message    = p_error_message,
        checksum_md5     = COALESCE(p_checksum_md5, checksum_md5),
        file_size        = COALESCE(p_file_size, file_size),
        migrated_at      = CASE WHEN p_status = 'success'  THEN NOW() ELSE migrated_at END,
        verified_at      = CASE WHEN p_status = 'verified' THEN NOW() ELSE verified_at END,
        updated_at       = NOW()
    WHERE scan_id = p_scan_id;

    UPDATE app.mr_scan
    SET
        oss_url          = COALESCE(p_oss_url, oss_url),
        file_size        = COALESCE(p_file_size, file_size),
        checksum_md5     = COALESCE(p_checksum_md5, checksum_md5),
        migration_status = CASE
            WHEN p_status = 'success'  THEN 'migrated'
            WHEN p_status = 'verified' THEN 'verified'
            WHEN p_status = 'rollback' THEN 'not_migrated'
            ELSE migration_status
        END,
        migrated_at = CASE WHEN p_status = 'success' THEN NOW() ELSE migrated_at END
    WHERE id = p_scan_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION app.update_migration_status(INTEGER, VARCHAR, TEXT, TEXT, VARCHAR, BIGINT)
    IS '更新迁移状态 — 同时更新日志表和主表';

-- ============================================
-- 7. 种子数据
-- ============================================

-- 7.1 角色
INSERT INTO app.mr_auth_role (code, name, description, permissions, sort_order)
VALUES
    ('ADMIN',  'System Administrator', 'Full user and permission management access',
     'user:manage,role:manage,record:manage,log:read,system:read,statistics:read', 1),
    ('DOCTOR', 'Doctor', 'Query and handle medical records',
     'record:edit,search:read,statistics:read', 2),
    ('NURSE',  'Nurse', 'Assist with basic queries and records',
     'record:read,search:read', 3)
ON CONFLICT (code) DO NOTHING;

-- 7.2 用户（bcrypt 密码哈希）
INSERT INTO app.mr_auth_user (username, display_name, password_hash, role_code, status)
VALUES
    ('br_admin', 'System Administrator', '$2a$12$1MBK2EugjPA4k45jzanZwOfP8WAHFW7Upb.EnqBIWhFoYp3tKx4za', 'ADMIN',  'active'),
    ('admin',    'System Administrator', '$2a$12$NiQwMT54aA1Un.FOjzVWR.5J/PDIGQHwp0nMEGatrdCerqfSvbHqS', 'ADMIN',  'active'),
    ('doctor1',  'Duty Doctor',          '$2a$12$Y2mlZdwNkLhUj5PeKKXVPuqlXW/HUX9rJ0uWtqOQQDm0ipmBYB21q', 'DOCTOR', 'active'),
    ('nurse1',   'Outpatient Nurse',     '$2a$12$YUwhuNhN4rj0p6jZP6RcoOD/IbVx/uZuhB597kngo/L3fxZL5vNbS', 'NURSE',  'active')
ON CONFLICT (username) DO UPDATE SET
    display_name  = EXCLUDED.display_name,
    password_hash = EXCLUDED.password_hash,
    role_code     = EXCLUDED.role_code,
    status        = EXCLUDED.status;
