CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.mr_scan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brxh TEXT,
    bah TEXT,
    sjh TEXT,
    filename TEXT,
    btype INTEGER,
    pages INTEGER,
    openerno TEXT,
    uploaddate TEXT,
    uploadflag INTEGER,
    folder TEXT
);

CREATE TABLE IF NOT EXISTS app.mr_statistics (
    bah TEXT,
    cid TEXT,
    openerno TEXT,
    date TEXT,
    type TEXT,
    pages INTEGER,
    sjh TEXT
);

CREATE TABLE IF NOT EXISTS app.mr_patient (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcard TEXT,
    bah TEXT,
    admissiontime TEXT,
    department TEXT,
    name TEXT
);

CREATE TABLE IF NOT EXISTS app.mr_user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    age INTEGER,
    email TEXT
);

CREATE TABLE IF NOT EXISTS app.mr_auth_role (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    permissions TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS app.mr_auth_user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    display_name TEXT,
    password_hash TEXT NOT NULL,
    role_code TEXT NOT NULL REFERENCES app.mr_auth_role (code) ON UPDATE CASCADE,
    status TEXT NOT NULL DEFAULT 'active',
    last_login_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app.access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT,
    client_ip TEXT,
    request_uri TEXT,
    method TEXT,
    user_agent TEXT,
    access_time TIMESTAMP WITHOUT TIME ZONE,
    query_string TEXT,
    request_body TEXT,
    response_status TEXT,
    execute_time BIGINT,
    referer TEXT
);

-- Migration: add username column if not exists (for existing databases)
ALTER TABLE app.access_log ADD COLUMN IF NOT EXISTS username TEXT;

CREATE INDEX IF NOT EXISTS idx_mr_scan_bah ON app.mr_scan (bah);
CREATE INDEX IF NOT EXISTS idx_mr_scan_brxh ON app.mr_scan (brxh);
CREATE INDEX IF NOT EXISTS idx_mr_scan_sjh ON app.mr_scan (sjh);
CREATE INDEX IF NOT EXISTS idx_mr_statistics_bah ON app.mr_statistics (bah);
CREATE INDEX IF NOT EXISTS idx_mr_statistics_date ON app.mr_statistics (date);
CREATE INDEX IF NOT EXISTS idx_mr_statistics_type ON app.mr_statistics (type);
CREATE INDEX IF NOT EXISTS idx_mr_statistics_sjh ON app.mr_statistics (sjh);
CREATE INDEX IF NOT EXISTS idx_mr_patient_idcard ON app.mr_patient (idcard);
CREATE INDEX IF NOT EXISTS idx_mr_auth_user_username ON app.mr_auth_user (username);
CREATE INDEX IF NOT EXISTS idx_mr_auth_user_role_code ON app.mr_auth_user (role_code);
CREATE INDEX IF NOT EXISTS idx_access_log_access_time ON app.access_log (access_time DESC);
CREATE INDEX IF NOT EXISTS idx_access_log_access_time_id ON app.access_log (access_time ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_access_log_client_ip ON app.access_log (client_ip);
CREATE INDEX IF NOT EXISTS idx_access_log_request_uri ON app.access_log (request_uri);
CREATE INDEX IF NOT EXISTS idx_access_log_method ON app.access_log (method);
CREATE INDEX IF NOT EXISTS idx_access_log_response_status ON app.access_log (response_status);
CREATE INDEX IF NOT EXISTS idx_access_log_method_status ON app.access_log (method, response_status);

-- ============================================
-- OSS Migration Support
-- Note: Column additions are handled via migration script (migration_to_oss.sql)
-- This file only contains base schema definitions
-- ============================================

INSERT INTO app.mr_auth_role (code, name, description, permissions, sort_order)
VALUES
    ('ADMIN', 'System Administrator', 'Full user and permission management access', 'user:manage,role:manage,record:manage,log:read,system:read,test:read,statistics:read', 1),
    ('DOCTOR', 'Doctor', 'Query and handle medical records', 'record:edit,search:read,statistics:read', 2),
    ('NURSE', 'Nurse', 'Assist with basic queries and records', 'record:read,search:read', 3)
ON CONFLICT (code) DO NOTHING;

INSERT INTO app.mr_auth_user (username, display_name, password_hash, role_code, status)
VALUES
	    ('br_admin', 'System Administrator', '$2a$12$1MBK2EugjPA4k45jzanZwOfP8WAHFW7Upb.EnqBIWhFoYp3tKx4za', 'ADMIN', 'active'),
	    ('admin', 'System Administrator', '$2a$12$NiQwMT54aA1Un.FOjzVWR.5J/PDIGQHwp0nMEGatrdCerqfSvbHqS', 'ADMIN', 'active'),
	    ('doctor1', 'Duty Doctor', '$2a$12$Y2mlZdwNkLhUj5PeKKXVPuqlXW/HUX9rJ0uWtqOQQDm0ipmBYB21q', 'DOCTOR', 'active'),
	    ('nurse1', 'Outpatient Nurse', '$2a$12$YUwhuNhN4rj0p6jZP6RcoOD/IbVx/uZuhB597kngo/L3fxZL5vNbS', 'NURSE', 'active')
ON CONFLICT (username) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    password_hash = EXCLUDED.password_hash,
    role_code = EXCLUDED.role_code,
    status = EXCLUDED.status;
