CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.mr_scan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brxh TEXT,
    bah TEXT,
    filename TEXT,
    btype INTEGER,
    pages INTEGER,
    openerno TEXT,
    uploaddate TEXT,
    uploadflag INTEGER,
    folder TEXT
);

CREATE TABLE IF NOT EXISTS app.mr_statistics (
    bah TEXT,
    cid TEXT,
    openerno TEXT,
    date TEXT,
    type TEXT,
    pages INTEGER
);

CREATE TABLE IF NOT EXISTS app.mr_patient (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idcard TEXT,
    bah TEXT,
    admissiontime TEXT,
    department TEXT,
    name TEXT
);

CREATE TABLE IF NOT EXISTS app.mr_user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    age INTEGER,
    email TEXT
);

CREATE TABLE IF NOT EXISTS app.access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_ip TEXT,
    request_uri TEXT,
    method TEXT,
    user_agent TEXT,
    access_time TIMESTAMP WITHOUT TIME ZONE,
    query_string TEXT,
    request_body TEXT,
    response_status TEXT,
    execute_time BIGINT,
    referer TEXT
);

CREATE INDEX IF NOT EXISTS idx_mr_scan_bah ON app.mr_scan (bah);
CREATE INDEX IF NOT EXISTS idx_mr_scan_brxh ON app.mr_scan (brxh);
CREATE INDEX IF NOT EXISTS idx_mr_statistics_bah ON app.mr_statistics (bah);
CREATE INDEX IF NOT EXISTS idx_mr_statistics_date ON app.mr_statistics (date);
CREATE INDEX IF NOT EXISTS idx_mr_statistics_type ON app.mr_statistics (type);
CREATE INDEX IF NOT EXISTS idx_mr_patient_idcard ON app.mr_patient (idcard);
CREATE INDEX IF NOT EXISTS idx_access_log_access_time ON app.access_log (access_time DESC);
CREATE INDEX IF NOT EXISTS idx_access_log_access_time_id ON app.access_log (access_time ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_access_log_client_ip ON app.access_log (client_ip);
CREATE INDEX IF NOT EXISTS idx_access_log_request_uri ON app.access_log (request_uri);
