SET MODE PostgreSQL;
CREATE SCHEMA IF NOT EXISTS app;
SET SCHEMA app;

CREATE TABLE IF NOT EXISTS mr_scan (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brxh        VARCHAR(255),
    bah         VARCHAR(255),
    sjh         VARCHAR(255),
    filename    VARCHAR(255),
    btype       INTEGER,
    pages       INTEGER,
    openerno    VARCHAR(255),
    uploaddate  VARCHAR(255),
    uploadflag  INTEGER,
    folder      VARCHAR(255),
    oss_url     VARCHAR(512),
    file_size   BIGINT,
    checksum_md5 VARCHAR(64),
    migration_status VARCHAR(32),
    migrated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mr_auth_role (
    code        VARCHAR(64) PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(512),
    permissions VARCHAR(1024) NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mr_auth_user (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    display_name  VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    role_code     VARCHAR(64) NOT NULL REFERENCES mr_auth_role (code) ON UPDATE CASCADE,
    status        VARCHAR(32) NOT NULL DEFAULT 'active',
    last_login_at TIMESTAMP,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS image_migration_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id           INTEGER,
    local_path        VARCHAR(1024),
    oss_url           VARCHAR(1024),
    migration_status  VARCHAR(32),
    error_message     TEXT,
    file_size         BIGINT,
    checksum_md5      VARCHAR(64),
    migrated_at       TIMESTAMP,
    verified_at       TIMESTAMP,
    created_at        TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS access_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(255),
    client_ip         VARCHAR(255),
    request_uri       VARCHAR(1024),
    method            VARCHAR(32),
    user_agent        VARCHAR(1024),
    access_time       TIMESTAMP,
    query_string      TEXT,
    request_body      TEXT,
    response_status   VARCHAR(32),
    execute_time      BIGINT,
    referer           VARCHAR(1024),
    audit_action      VARCHAR(64),
    audit_target      VARCHAR(255),
    audit_description VARCHAR(512)
);

INSERT INTO mr_auth_role (code, name, description, permissions, sort_order)
VALUES ('ADMIN', 'Administrator', 'Full access', 'user:manage,role:manage,record:manage,log:read,system:read,test:read,statistics:read', 1),
       ('DOCTOR', 'Doctor', 'Doctor access', 'record:edit,search:read,statistics:read', 2);

DELETE FROM mr_scan;
ALTER TABLE mr_scan ALTER COLUMN id RESTART WITH 1;
DELETE FROM access_log;
ALTER TABLE access_log ALTER COLUMN id RESTART WITH 1;
