SET MODE PostgreSQL;
CREATE SCHEMA IF NOT EXISTS app;
SET SCHEMA app;

CREATE TABLE IF NOT EXISTS mr_archive (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sjh                    VARCHAR(64),
    bah                    VARCHAR(64),
    patient_id             VARCHAR(64),
    patient_name           VARCHAR(100),
    inpatient_department   VARCHAR(100),
    device_id              VARCHAR(64),
    operator_no            VARCHAR(64),
    archive_date           DATE,
    discharge_date         DATE,
    archive_type           VARCHAR(64),
    page_count             INTEGER,
    source_statistics_id   INTEGER,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mr_scan (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id  BIGINT REFERENCES mr_archive(id),
    brxh        VARCHAR(255),
    bah         VARCHAR(255),
    sjh         VARCHAR(255),
    filename    VARCHAR(255),
    btype       INTEGER,
    pages       INTEGER,
    openerno    VARCHAR(255),
    uploaddate  VARCHAR(255),
    uploadflag  INTEGER,
    folder      VARCHAR(255),
    oss_url     VARCHAR(512),
    file_size   BIGINT,
    checksum_md5 VARCHAR(64),
    migration_status VARCHAR(32),
    migrated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mr_record_type_dict (
    btype               SMALLINT PRIMARY KEY,
    type_code           VARCHAR(64) NOT NULL UNIQUE,
    type_name           VARCHAR(100) NOT NULL,
    keywords            TEXT NOT NULL DEFAULT '',
    negative_keywords   TEXT NOT NULL DEFAULT '',
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order          INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mr_classification_job (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id          BIGINT NOT NULL REFERENCES mr_archive(id),
    scope_type          VARCHAR(24) NOT NULL DEFAULT 'UNCLASSIFIED',
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    total_count         BIGINT NOT NULL DEFAULT 0,
    processed_count     BIGINT NOT NULL DEFAULT 0,
    suggested_count     BIGINT NOT NULL DEFAULT 0,
    no_match_count      BIGINT NOT NULL DEFAULT 0,
    failed_count        BIGINT NOT NULL DEFAULT 0,
    cursor_scan_id      INTEGER,
    model_version       VARCHAR(64),
    error_message       TEXT,
    created_by          VARCHAR(64),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at          TIMESTAMP WITH TIME ZONE,
    completed_at        TIMESTAMP WITH TIME ZONE,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mr_image_classification (
    scan_id              INTEGER PRIMARY KEY REFERENCES mr_scan(id),
    archive_id           BIGINT NOT NULL REFERENCES mr_archive(id),
    predicted_btype      SMALLINT REFERENCES mr_record_type_dict(btype),
    confidence           NUMERIC(6,5),
    classification_state VARCHAR(24) NOT NULL DEFAULT 'UNPROCESSED',
    effective_source     VARCHAR(32),
    model_version        VARCHAR(64),
    rule_version         VARCHAR(64),
    ocr_title            TEXT,
    evidence             JSON DEFAULT '{}',
    image_checksum       VARCHAR(32),
    reviewed_btype       SMALLINT REFERENCES mr_record_type_dict(btype),
    reviewed_by          VARCHAR(64),
    reviewed_at          TIMESTAMP WITH TIME ZONE,
    error_message        TEXT,
    classified_at        TIMESTAMP WITH TIME ZONE,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mr_image_type_audit (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id             INTEGER NOT NULL REFERENCES mr_scan(id),
    archive_id          BIGINT REFERENCES mr_archive(id),
    previous_btype      SMALLINT,
    proposed_btype      SMALLINT,
    final_btype         SMALLINT,
    action              VARCHAR(32) NOT NULL,
    source              VARCHAR(32) NOT NULL,
    model_version       VARCHAR(64),
    confidence          NUMERIC(6,5),
    operated_by         VARCHAR(64),
    reason              TEXT,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

MERGE INTO mr_record_type_dict KEY(btype) VALUES
    (0, 'unclassified', '未分类', '', '', FALSE, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 'record_home', '病案首页', '住院病案首页|病案首页', '', TRUE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'progress_note', '病程记录', '首次病程记录|日常病程记录|病程记录', '术后首次病程记录', TRUE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'postoperative', '术后病程', '术后首次病程记录|术后病程记录', '', TRUE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14, 'other', '其它', '', '', TRUE, 140, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS mr_auth_role (
    code        VARCHAR(64) PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(512),
    permissions VARCHAR(1024) NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mr_auth_user (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    display_name  VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    role_code     VARCHAR(64) NOT NULL REFERENCES mr_auth_role (code) ON UPDATE CASCADE,
    status        VARCHAR(32) NOT NULL DEFAULT 'active',
    last_login_at TIMESTAMP,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS image_migration_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id           INTEGER,
    local_path        VARCHAR(1024),
    oss_url           VARCHAR(1024),
    migration_status  VARCHAR(32),
    error_message     TEXT,
    file_size         BIGINT,
    checksum_md5      VARCHAR(64),
    migrated_at       TIMESTAMP,
    verified_at       TIMESTAMP,
    created_at        TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS access_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(255),
    client_ip         VARCHAR(255),
    request_uri       VARCHAR(1024),
    method            VARCHAR(32),
    user_agent        VARCHAR(1024),
    access_time       TIMESTAMP,
    query_string      TEXT,
    request_body      TEXT,
    response_status   VARCHAR(32),
    execute_time      BIGINT,
    referer           VARCHAR(1024),
    audit_action      VARCHAR(64),
    audit_target      VARCHAR(255),
    audit_description VARCHAR(512)
);

INSERT INTO mr_auth_role (code, name, description, permissions, sort_order)
VALUES ('ADMIN', 'Administrator', 'Full access', 'user:manage,role:manage,record:manage,log:read,system:read,test:read,statistics:read', 1),
       ('DOCTOR', 'Doctor', 'Doctor access', 'record:edit,search:read,statistics:read', 2);

DELETE FROM mr_image_type_audit;
DELETE FROM mr_image_classification;
DELETE FROM mr_classification_job;
DELETE FROM mr_scan;
DELETE FROM mr_archive;
ALTER TABLE mr_scan ALTER COLUMN id RESTART WITH 1;
ALTER TABLE mr_archive ALTER COLUMN id RESTART WITH 1;
DELETE FROM access_log;
ALTER TABLE access_log ALTER COLUMN id RESTART WITH 1;
