export const lightTheme = {
  'color-scheme': 'light',
  '--radius': '10px',
  // Core semantic colors
  '--background': '210 33% 98%',
  '--foreground': '215 28% 17%',
  '--card': '0 0% 100%',
  '--card-foreground': '215 28% 17%',
  '--popover': '0 0% 100%',
  '--popover-foreground': '215 28% 17%',
  '--primary': '203 89% 39%',
  '--primary-foreground': '0 0% 100%',
  '--secondary': '210 40% 96%',
  '--secondary-foreground': '215 25% 27%',
  '--muted': '210 32% 96%',
  '--muted-foreground': '215 16% 44%',
  '--accent': '199 89% 95%',
  '--accent-foreground': '203 89% 30%',
  '--destructive': '0 72% 51%',
  '--destructive-foreground': '0 0% 100%',
  '--success': '152 69% 31%',
  '--success-foreground': '0 0% 100%',
  '--warning': '32 95% 44%',
  '--warning-foreground': '24 100% 12%',
  '--info': '188 86% 34%',
  '--info-foreground': '0 0% 100%',
  '--border': '214 28% 89%',
  '--input': '214 28% 86%',
  '--ring': '203 89% 39%',
  // Application shell
  '--g-main-area-bg': 'hsl(210 30% 96%)',
  '--g-header-bg': 'hsl(var(--card))',
  '--g-header-color': 'hsl(var(--foreground))',
  '--g-header-menu-color': 'hsl(var(--muted-foreground))',
  '--g-header-menu-hover-bg': 'hsl(var(--accent))',
  '--g-header-menu-hover-color': 'hsl(var(--accent-foreground))',
  '--g-header-menu-active-bg': 'hsl(var(--primary))',
  '--g-header-menu-active-color': 'hsl(var(--primary-foreground))',
  '--g-main-sidebar-bg': 'hsl(var(--card))',
  '--g-main-sidebar-menu-color': 'hsl(var(--muted-foreground))',
  '--g-main-sidebar-menu-hover-bg': 'hsl(var(--accent))',
  '--g-main-sidebar-menu-hover-color': 'hsl(var(--accent-foreground))',
  '--g-main-sidebar-menu-active-bg': 'hsl(var(--primary))',
  '--g-main-sidebar-menu-active-color': 'hsl(var(--primary-foreground))',
  '--g-sub-sidebar-bg': 'hsl(var(--card))',
  '--g-sub-sidebar-menu-color': 'hsl(var(--muted-foreground))',
  '--g-sub-sidebar-menu-hover-bg': 'hsl(var(--accent))',
  '--g-sub-sidebar-menu-hover-color': 'hsl(var(--accent-foreground))',
  '--g-sub-sidebar-menu-active-bg': 'hsl(var(--primary))',
  '--g-sub-sidebar-menu-active-color': 'hsl(var(--primary-foreground))',
  '--g-tabbar-bg': 'var(--g-main-area-bg)',
  '--g-tabbar-dividers-bg': 'hsl(var(--border))',
  '--g-tabbar-tab-color': 'hsl(var(--muted-foreground))',
  '--g-tabbar-tab-hover-bg': 'hsl(var(--accent))',
  '--g-tabbar-tab-hover-color': 'hsl(var(--accent-foreground))',
  '--g-tabbar-tab-active-bg': 'hsl(var(--card))',
  '--g-tabbar-tab-active-color': 'hsl(var(--foreground))',
  '--g-toolbar-bg': 'hsl(var(--card))',
}

export const darkTheme = {
  'color-scheme': 'dark',
  '--radius': '10px',
  // Core semantic colors
  '--background': '222 32% 8%',
  '--foreground': '210 20% 96%',
  '--card': '222 27% 11%',
  '--card-foreground': '210 20% 96%',
  '--popover': '222 27% 11%',
  '--popover-foreground': '210 20% 96%',
  '--primary': '203 89% 45%',
  '--primary-foreground': '0 0% 100%',
  '--secondary': '217 23% 17%',
  '--secondary-foreground': '210 20% 94%',
  '--muted': '217 23% 17%',
  '--muted-foreground': '215 16% 68%',
  '--accent': '203 40% 18%',
  '--accent-foreground': '200 90% 82%',
  '--destructive': '0 62% 43%',
  '--destructive-foreground': '0 0% 100%',
  '--success': '152 60% 45%',
  '--success-foreground': '222 32% 8%',
  '--warning': '32 95% 58%',
  '--warning-foreground': '24 100% 12%',
  '--info': '188 78% 50%',
  '--info-foreground': '222 32% 8%',
  '--border': '217 19% 22%',
  '--input': '217 19% 25%',
  '--ring': '200 92% 65%',
  // Application shell
  '--g-main-area-bg': 'hsl(222 32% 7%)',
  '--g-header-bg': 'hsl(var(--card))',
  '--g-header-color': 'hsl(var(--foreground))',
  '--g-header-menu-color': 'hsl(var(--muted-foreground))',
  '--g-header-menu-hover-bg': 'hsl(var(--accent))',
  '--g-header-menu-hover-color': 'hsl(var(--accent-foreground))',
  '--g-header-menu-active-bg': 'hsl(var(--primary))',
  '--g-header-menu-active-color': 'hsl(var(--primary-foreground))',
  '--g-main-sidebar-bg': 'hsl(var(--card))',
  '--g-main-sidebar-menu-color': 'hsl(var(--muted-foreground))',
  '--g-main-sidebar-menu-hover-bg': 'hsl(var(--accent))',
  '--g-main-sidebar-menu-hover-color': 'hsl(var(--accent-foreground))',
  '--g-main-sidebar-menu-active-bg': 'hsl(var(--primary))',
  '--g-main-sidebar-menu-active-color': 'hsl(var(--primary-foreground))',
  '--g-sub-sidebar-bg': 'hsl(var(--card))',
  '--g-sub-sidebar-menu-color': 'hsl(var(--muted-foreground))',
  '--g-sub-sidebar-menu-hover-bg': 'hsl(var(--accent))',
  '--g-sub-sidebar-menu-hover-color': 'hsl(var(--accent-foreground))',
  '--g-sub-sidebar-menu-active-bg': 'hsl(var(--primary))',
  '--g-sub-sidebar-menu-active-color': 'hsl(var(--primary-foreground))',
  '--g-tabbar-bg': 'var(--g-main-area-bg)',
  '--g-tabbar-dividers-bg': 'hsl(var(--border))',
  '--g-tabbar-tab-color': 'hsl(var(--muted-foreground))',
  '--g-tabbar-tab-hover-bg': 'hsl(var(--accent))',
  '--g-tabbar-tab-hover-color': 'hsl(var(--accent-foreground))',
  '--g-tabbar-tab-active-bg': 'hsl(var(--card))',
  '--g-tabbar-tab-active-color': 'hsl(var(--foreground))',
  '--g-toolbar-bg': 'hsl(var(--card))',
}
