-- ============================================================
-- MRR V0.5 数据交换中心
--
-- 支持：
-- 1. mr_statistics 中等规模 CSV 导入/导出；
-- 2. mr_scan 数千万行 CSV 分文件、分任务导入/导出；
-- 3. 任务进度、文件级断点、错误样本和导入来源追踪；
-- 4. 通过 UNLOGGED staging + PostgreSQL COPY 避免逐行 INSERT。
-- ============================================================

CREATE TABLE app.data_transfer_job (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direction           VARCHAR(16) NOT NULL,
    entity_type         VARCHAR(32) NOT NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    import_mode         VARCHAR(16) NOT NULL DEFAULT 'SKIP_DUPLICATES',
    source_type         VARCHAR(16),
    total_files         INTEGER NOT NULL DEFAULT 0,
    completed_files     INTEGER NOT NULL DEFAULT 0,
    total_rows          BIGINT NOT NULL DEFAULT 0,
    processed_rows      BIGINT NOT NULL DEFAULT 0,
    valid_rows          BIGINT NOT NULL DEFAULT 0,
    invalid_rows        BIGINT NOT NULL DEFAULT 0,
    inserted_rows       BIGINT NOT NULL DEFAULT 0,
    updated_rows        BIGINT NOT NULL DEFAULT 0,
    skipped_rows        BIGINT NOT NULL DEFAULT 0,
    progress            NUMERIC(6, 2) NOT NULL DEFAULT 0,
    current_stage       VARCHAR(64),
    current_file_no     INTEGER,
    options             JSONB NOT NULL DEFAULT '{}'::JSONB,
    error_message       TEXT,
    created_by          VARCHAR(64),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    heartbeat_at        TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_data_transfer_direction
        CHECK (direction IN ('IMPORT', 'EXPORT')),
    CONSTRAINT ck_data_transfer_entity
        CHECK (entity_type IN ('MR_STATISTICS', 'MR_SCAN')),
    CONSTRAINT ck_data_transfer_status
        CHECK (status IN (
            'CREATED', 'UPLOADING', 'UPLOADED', 'VALIDATING',
            'WAITING_CONFIRM', 'IMPORTING', 'EXPORTING', 'MERGING',
            'PAUSED', 'CANCELLED', 'COMPLETED',
            'COMPLETED_WITH_ERRORS', 'FAILED'
        )),
    CONSTRAINT ck_data_transfer_import_mode
        CHECK (import_mode IN ('SKIP_DUPLICATES', 'UPSERT')),
    CONSTRAINT ck_data_transfer_counts CHECK (
        total_files >= 0 AND completed_files >= 0
        AND total_rows >= 0 AND processed_rows >= 0
        AND valid_rows >= 0 AND invalid_rows >= 0
        AND inserted_rows >= 0 AND updated_rows >= 0 AND skipped_rows >= 0
    ),
    CONSTRAINT ck_data_transfer_progress CHECK (progress >= 0 AND progress <= 100)
);

COMMENT ON TABLE app.data_transfer_job IS 'CSV 数据导入导出任务';
COMMENT ON COLUMN app.data_transfer_job.entity_type IS '受控数据类型：MR_STATISTICS/MR_SCAN';
COMMENT ON COLUMN app.data_transfer_job.options IS '导入导出筛选和执行参数，不接受原始 SQL';

CREATE INDEX idx_data_transfer_job_created_at
    ON app.data_transfer_job (created_at DESC);
CREATE INDEX idx_data_transfer_job_status
    ON app.data_transfer_job (status, created_at DESC);
CREATE INDEX idx_data_transfer_job_entity
    ON app.data_transfer_job (entity_type, direction, created_at DESC);

CREATE TABLE app.data_transfer_file (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id              BIGINT NOT NULL
        REFERENCES app.data_transfer_job(id) ON DELETE CASCADE,
    sequence_no         INTEGER NOT NULL,
    original_filename   VARCHAR(512) NOT NULL,
    stored_path         TEXT NOT NULL,
    download_name       VARCHAR(512),
    file_size           BIGINT NOT NULL DEFAULT 0,
    sha256              VARCHAR(64),
    status              VARCHAR(32) NOT NULL DEFAULT 'UPLOADED',
    total_rows          BIGINT NOT NULL DEFAULT 0,
    processed_rows      BIGINT NOT NULL DEFAULT 0,
    valid_rows          BIGINT NOT NULL DEFAULT 0,
    invalid_rows        BIGINT NOT NULL DEFAULT 0,
    inserted_rows       BIGINT NOT NULL DEFAULT 0,
    updated_rows        BIGINT NOT NULL DEFAULT 0,
    skipped_rows        BIGINT NOT NULL DEFAULT 0,
    first_record_id     BIGINT,
    last_record_id      BIGINT,
    error_message       TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (job_id, sequence_no),
    CONSTRAINT ck_data_transfer_file_status CHECK (status IN (
        'UPLOADING', 'UPLOADED', 'VALIDATING', 'IMPORTING', 'EXPORTING',
        'COMPLETED', 'COMPLETED_WITH_ERRORS', 'SKIPPED', 'FAILED'
    )),
    CONSTRAINT ck_data_transfer_file_counts CHECK (
        file_size >= 0 AND total_rows >= 0 AND processed_rows >= 0
        AND valid_rows >= 0 AND invalid_rows >= 0
        AND inserted_rows >= 0 AND updated_rows >= 0 AND skipped_rows >= 0
    )
);

COMMENT ON TABLE app.data_transfer_file IS '数据交换任务的输入或输出文件，支持文件级断点恢复';
CREATE INDEX idx_data_transfer_file_job
    ON app.data_transfer_file (job_id, sequence_no);
CREATE INDEX idx_data_transfer_file_status
    ON app.data_transfer_file (status, created_at);

CREATE TABLE app.data_transfer_error (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          BIGINT NOT NULL
        REFERENCES app.data_transfer_job(id) ON DELETE CASCADE,
    file_id         BIGINT
        REFERENCES app.data_transfer_file(id) ON DELETE CASCADE,
    source_row_no   BIGINT,
    field_name      VARCHAR(128),
    error_code      VARCHAR(64) NOT NULL,
    error_message   VARCHAR(1000) NOT NULL,
    raw_data        JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE app.data_transfer_error IS '导入错误样本；完整错误行由 CSV 错误报告保存';
CREATE INDEX idx_data_transfer_error_job
    ON app.data_transfer_error (job_id, id);

ALTER TABLE app.mr_statistics
    ADD COLUMN IF NOT EXISTS import_job_id BIGINT,
    ADD COLUMN IF NOT EXISTS source_row_hash VARCHAR(32);

ALTER TABLE app.mr_statistics
    ADD CONSTRAINT fk_mr_statistics_import_job
    FOREIGN KEY (import_job_id)
    REFERENCES app.data_transfer_job(id)
    ON DELETE SET NULL
    NOT VALID;

CREATE UNIQUE INDEX IF NOT EXISTS ux_mr_statistics_source_row_hash
    ON app.mr_statistics (source_row_hash)
    WHERE source_row_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mr_statistics_import_job
    ON app.mr_statistics (import_job_id)
    WHERE import_job_id IS NOT NULL;

ALTER TABLE app.mr_scan
    ADD COLUMN IF NOT EXISTS import_job_id BIGINT,
    ADD COLUMN IF NOT EXISTS source_record_key VARCHAR(32);

ALTER TABLE app.mr_scan
    ADD CONSTRAINT fk_mr_scan_import_job
    FOREIGN KEY (import_job_id)
    REFERENCES app.data_transfer_job(id)
    ON DELETE SET NULL
    NOT VALID;

-- 历史数据保持 NULL；只保证经数据交换中心写入的新记录不重复。
CREATE UNIQUE INDEX IF NOT EXISTS ux_mr_scan_source_record_key
    ON app.mr_scan (source_record_key)
    WHERE source_record_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mr_scan_import_job
    ON app.mr_scan (import_job_id)
    WHERE import_job_id IS NOT NULL;

-- job_id/file_id 由执行 COPY 的数据库会话参数提供。
CREATE UNLOGGED TABLE app.stg_mr_statistics_import (
    row_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id                  BIGINT NOT NULL
        DEFAULT current_setting('app.data_transfer_job_id')::BIGINT,
    file_id                 BIGINT NOT NULL
        DEFAULT current_setting('app.data_transfer_file_id')::BIGINT,
    bah_raw                 TEXT,
    cid_raw                 TEXT,
    openerno_raw            TEXT,
    date_raw                TEXT,
    type_raw                TEXT,
    pages_raw               TEXT,
    sjh_raw                 TEXT,
    patientname_raw         TEXT,
    inpatientdepartment_raw TEXT,
    patientid_raw           TEXT,
    dischargedate_raw       TEXT,
    bah                     TEXT,
    sjh                     TEXT,
    archive_date            DATE,
    discharge_date          DATE,
    pages                   INTEGER,
    source_row_hash         VARCHAR(32),
    is_valid                BOOLEAN,
    error_code              VARCHAR(64),
    error_message           TEXT
);

CREATE INDEX idx_stg_statistics_job_file
    ON app.stg_mr_statistics_import (job_id, file_id, row_id);
CREATE INDEX idx_stg_statistics_hash
    ON app.stg_mr_statistics_import (source_row_hash)
    WHERE source_row_hash IS NOT NULL;

CREATE UNLOGGED TABLE app.stg_mr_scan_import (
    row_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id              BIGINT NOT NULL
        DEFAULT current_setting('app.data_transfer_job_id')::BIGINT,
    file_id             BIGINT NOT NULL
        DEFAULT current_setting('app.data_transfer_file_id')::BIGINT,
    brxh_raw            TEXT,
    bah_raw             TEXT,
    sjh_raw             TEXT,
    filename_raw        TEXT,
    btype_raw           TEXT,
    pages_raw           TEXT,
    openerno_raw        TEXT,
    uploaddate_raw      TEXT,
    uploadflag_raw      TEXT,
    folder_raw          TEXT,
    brxh                TEXT,
    bah                 TEXT,
    sjh                 TEXT,
    btype               INTEGER,
    pages               INTEGER,
    uploadflag          INTEGER,
    upload_date         DATE,
    archive_id          BIGINT,
    source_record_key   VARCHAR(32),
    is_valid            BOOLEAN,
    error_code          VARCHAR(64),
    error_message       TEXT
);

CREATE INDEX idx_stg_scan_job_file
    ON app.stg_mr_scan_import (job_id, file_id, row_id);
CREATE INDEX idx_stg_scan_sjh
    ON app.stg_mr_scan_import (job_id, file_id, sjh)
    WHERE sjh IS NOT NULL;
CREATE INDEX idx_stg_scan_bah
    ON app.stg_mr_scan_import (job_id, file_id, bah)
    WHERE bah IS NOT NULL;
CREATE INDEX idx_stg_scan_source_key
    ON app.stg_mr_scan_import (source_record_key)
    WHERE source_record_key IS NOT NULL;

CREATE OR REPLACE VIEW app.v_data_transfer_job_summary AS
SELECT
    j.id,
    j.direction,
    j.entity_type,
    j.status,
    j.import_mode,
    j.source_type,
    j.total_files,
    j.completed_files,
    j.total_rows,
    j.processed_rows,
    j.valid_rows,
    j.invalid_rows,
    j.inserted_rows,
    j.updated_rows,
    j.skipped_rows,
    j.progress,
    j.current_stage,
    j.current_file_no,
    j.error_message,
    j.created_by,
    j.created_at,
    j.started_at,
    j.completed_at,
    j.heartbeat_at,
    j.updated_at,
    COUNT(f.id) FILTER (WHERE f.status = 'FAILED') AS failed_files
FROM app.data_transfer_job j
LEFT JOIN app.data_transfer_file f ON f.job_id = j.id
GROUP BY j.id;

COMMENT ON VIEW app.v_data_transfer_job_summary IS '数据交换任务进度与失败文件汇总';
