-- 病案访问 userid 与每日 IP 绑定。
-- 首次访问绑定当前 IP；后续 IP 切换次数由系统设置 archiveIpMaxChanges 控制。

CREATE TABLE IF NOT EXISTS app.mr_archive_ip_binding (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_date      DATE NOT NULL,
    userid           VARCHAR(128) NOT NULL,
    bound_ip         VARCHAR(64) NOT NULL,
    ip_change_count  INTEGER NOT NULL DEFAULT 0,
    first_access_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    last_access_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_archive_ip_binding_date_user UNIQUE (access_date, userid),
    CONSTRAINT ck_archive_ip_change_count_nonnegative CHECK (ip_change_count >= 0)
);

COMMENT ON TABLE app.mr_archive_ip_binding IS '病案访问用户每日 IP 绑定状态';
COMMENT ON COLUMN app.mr_archive_ip_binding.access_date IS '绑定生效日期，每日自动形成新的绑定记录';
COMMENT ON COLUMN app.mr_archive_ip_binding.userid IS '调用方通过 archive URL 明文传入的用户 ID';
COMMENT ON COLUMN app.mr_archive_ip_binding.bound_ip IS '当前允许访问的客户端 IP';
COMMENT ON COLUMN app.mr_archive_ip_binding.ip_change_count IS '当日已允许的 IP 切换次数';

CREATE INDEX IF NOT EXISTS idx_archive_ip_binding_user_date
    ON app.mr_archive_ip_binding (userid, access_date DESC);

INSERT INTO app.mr_system_settings (setting_key, setting_value, description, updated_by)
VALUES ('archiveIpMaxChanges', '3', '同一 userid 每日允许的 IP 切换次数', 'migration')
ON CONFLICT (setting_key) DO NOTHING;
