-- ============================================================
-- MRR V0.1 病案主数据重构（兼容式）
--
-- 目标：
-- 1. 使用 mr_archive 作为病案主实体；
-- 2. mr_statistics / mr_scan / mr_archive_box_record 通过 archive_id 关联；
-- 3. 保留旧字段，兼容现有 Excel 与 SQL 导入；
-- 4. 缺失上架号统一表示为 NULL，不生成虚假编号；
-- 5. 大体量 mr_scan 数据通过批处理函数渐进回填，避免 Flyway 长事务更新全表。
--
-- 版本使用 V0_1，确保后续 OSS 迁移 V1 仍可按顺序执行。
-- ============================================================

CREATE OR REPLACE FUNCTION app.normalize_medical_record_code(p_value TEXT)
RETURNS TEXT
LANGUAGE SQL
IMMUTABLE
PARALLEL SAFE
AS $$
SELECT CASE
    WHEN NULLIF(BTRIM(p_value), '') IS NULL THEN NULL
    WHEN BTRIM(p_value) ~ '^[0-9]{1,8}$' THEN LPAD(BTRIM(p_value), 8, '0')
    ELSE BTRIM(p_value)
END
$$;

COMMENT ON FUNCTION app.normalize_medical_record_code(TEXT)
    IS '规范化病案号/上架号：空白转 NULL，1~8 位纯数字补齐为 8 位';

CREATE OR REPLACE FUNCTION app.try_parse_date(p_value TEXT)
RETURNS DATE
LANGUAGE plpgsql
IMMUTABLE
PARALLEL SAFE
AS $$
DECLARE
    parts TEXT[];
BEGIN
    IF NULLIF(BTRIM(p_value), '') IS NULL THEN
        RETURN NULL;
    END IF;

    parts := regexp_match(BTRIM(p_value), '^(\d{4})[-/](\d{1,2})[-/](\d{1,2})$');
    IF parts IS NULL THEN
        RETURN NULL;
    END IF;

    RETURN make_date(parts[1]::INTEGER, parts[2]::INTEGER, parts[3]::INTEGER);
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END;
$$;

COMMENT ON FUNCTION app.try_parse_date(TEXT)
    IS '安全解析 YYYY-MM-DD 或 YYYY/MM/DD，非法值返回 NULL';

CREATE TABLE IF NOT EXISTS app.mr_archive (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sjh                    VARCHAR(64),
    bah                    VARCHAR(64),
    patient_id             VARCHAR(64),
    patient_name           VARCHAR(100),
    inpatient_department   VARCHAR(100),
    device_id              VARCHAR(64),
    operator_no            VARCHAR(64),
    archive_date           DATE,
    discharge_date         DATE,
    archive_type           VARCHAR(64),
    page_count             INTEGER,
    source_statistics_id   INTEGER REFERENCES app.mr_statistics(id) ON DELETE SET NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_mr_archive_sjh_not_blank CHECK (sjh IS NULL OR BTRIM(sjh) <> ''),
    CONSTRAINT chk_mr_archive_bah_not_blank CHECK (bah IS NULL OR BTRIM(bah) <> ''),
    CONSTRAINT chk_mr_archive_code_present CHECK (sjh IS NOT NULL OR bah IS NOT NULL),
    CONSTRAINT chk_mr_archive_page_count CHECK (page_count IS NULL OR page_count >= 0),
    CONSTRAINT uq_mr_archive_source_statistics UNIQUE (source_statistics_id)
);

COMMENT ON TABLE app.mr_archive IS '病案主表：统一承载上架号、病案号、患者和归档元数据';
COMMENT ON COLUMN app.mr_archive.sjh IS '上架号；允许缺失，非空值唯一';
COMMENT ON COLUMN app.mr_archive.bah IS '病案号；可能因历史规则重复，不能单独作为主键';
COMMENT ON COLUMN app.mr_archive.source_statistics_id IS '无上架号记录的原始统计行，用于稳定回填和追踪';

CREATE UNIQUE INDEX IF NOT EXISTS ux_mr_archive_sjh
    ON app.mr_archive (sjh)
    WHERE sjh IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_mr_archive_bah
    ON app.mr_archive (bah);

CREATE INDEX IF NOT EXISTS idx_mr_archive_patient_id
    ON app.mr_archive (patient_id)
    WHERE patient_id IS NOT NULL;

ALTER TABLE app.mr_statistics
    ADD COLUMN IF NOT EXISTS archive_id BIGINT;

ALTER TABLE app.mr_scan
    ADD COLUMN IF NOT EXISTS archive_id BIGINT;

ALTER TABLE app.mr_archive_box_record
    ADD COLUMN IF NOT EXISTS archive_id BIGINT;

-- 统计表规模相对可控，先建立主数据。非空上架号按上架号合并；缺失上架号按原始统计行保留。
INSERT INTO app.mr_archive (
    sjh,
    bah,
    patient_id,
    patient_name,
    inpatient_department,
    device_id,
    operator_no,
    archive_date,
    discharge_date,
    archive_type,
    page_count
)
SELECT
    app.normalize_medical_record_code(s.sjh) AS sjh,
    MAX(app.normalize_medical_record_code(s.bah)) AS bah,
    MAX(NULLIF(BTRIM(s.patientid), '')) AS patient_id,
    MAX(NULLIF(BTRIM(s.patientname), '')) AS patient_name,
    MAX(NULLIF(BTRIM(s.inpatientdepartment), '')) AS inpatient_department,
    MAX(NULLIF(BTRIM(s.cid), '')) AS device_id,
    MAX(NULLIF(BTRIM(s.openerno), '')) AS operator_no,
    MAX(app.try_parse_date(s.date)) AS archive_date,
    MAX(app.try_parse_date(s.dischargedate)) AS discharge_date,
    MAX(NULLIF(BTRIM(s.type), '')) AS archive_type,
    MAX(s.pages) AS page_count
FROM app.mr_statistics s
WHERE app.normalize_medical_record_code(s.sjh) IS NOT NULL
GROUP BY app.normalize_medical_record_code(s.sjh)
ON CONFLICT (sjh) WHERE sjh IS NOT NULL DO UPDATE
SET
    bah = COALESCE(EXCLUDED.bah, app.mr_archive.bah),
    patient_id = COALESCE(EXCLUDED.patient_id, app.mr_archive.patient_id),
    patient_name = COALESCE(EXCLUDED.patient_name, app.mr_archive.patient_name),
    inpatient_department = COALESCE(EXCLUDED.inpatient_department, app.mr_archive.inpatient_department),
    device_id = COALESCE(EXCLUDED.device_id, app.mr_archive.device_id),
    operator_no = COALESCE(EXCLUDED.operator_no, app.mr_archive.operator_no),
    archive_date = COALESCE(EXCLUDED.archive_date, app.mr_archive.archive_date),
    discharge_date = COALESCE(EXCLUDED.discharge_date, app.mr_archive.discharge_date),
    archive_type = COALESCE(EXCLUDED.archive_type, app.mr_archive.archive_type),
    page_count = COALESCE(EXCLUDED.page_count, app.mr_archive.page_count),
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO app.mr_archive (
    sjh,
    bah,
    patient_id,
    patient_name,
    inpatient_department,
    device_id,
    operator_no,
    archive_date,
    discharge_date,
    archive_type,
    page_count,
    source_statistics_id
)
SELECT
    NULL,
    app.normalize_medical_record_code(s.bah),
    NULLIF(BTRIM(s.patientid), ''),
    NULLIF(BTRIM(s.patientname), ''),
    NULLIF(BTRIM(s.inpatientdepartment), ''),
    NULLIF(BTRIM(s.cid), ''),
    NULLIF(BTRIM(s.openerno), ''),
    app.try_parse_date(s.date),
    app.try_parse_date(s.dischargedate),
    NULLIF(BTRIM(s.type), ''),
    s.pages,
    s.id
FROM app.mr_statistics s
WHERE app.normalize_medical_record_code(s.sjh) IS NULL
  AND app.normalize_medical_record_code(s.bah) IS NOT NULL
ON CONFLICT (source_statistics_id) DO UPDATE
SET
    bah = COALESCE(EXCLUDED.bah, app.mr_archive.bah),
    patient_id = COALESCE(EXCLUDED.patient_id, app.mr_archive.patient_id),
    patient_name = COALESCE(EXCLUDED.patient_name, app.mr_archive.patient_name),
    inpatient_department = COALESCE(EXCLUDED.inpatient_department, app.mr_archive.inpatient_department),
    device_id = COALESCE(EXCLUDED.device_id, app.mr_archive.device_id),
    operator_no = COALESCE(EXCLUDED.operator_no, app.mr_archive.operator_no),
    archive_date = COALESCE(EXCLUDED.archive_date, app.mr_archive.archive_date),
    discharge_date = COALESCE(EXCLUDED.discharge_date, app.mr_archive.discharge_date),
    archive_type = COALESCE(EXCLUDED.archive_type, app.mr_archive.archive_type),
    page_count = COALESCE(EXCLUDED.page_count, app.mr_archive.page_count),
    updated_at = CURRENT_TIMESTAMP;

UPDATE app.mr_statistics s
SET archive_id = a.id
FROM app.mr_archive a
WHERE s.archive_id IS NULL
  AND app.normalize_medical_record_code(s.sjh) IS NOT NULL
  AND a.sjh = app.normalize_medical_record_code(s.sjh);

UPDATE app.mr_statistics s
SET archive_id = a.id
FROM app.mr_archive a
WHERE s.archive_id IS NULL
  AND a.source_statistics_id = s.id;

CREATE OR REPLACE FUNCTION app.resolve_archive_id(
    p_bah TEXT,
    p_sjh TEXT,
    p_create_when_sjh_present BOOLEAN DEFAULT FALSE
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    normalized_bah TEXT := app.normalize_medical_record_code(p_bah);
    normalized_sjh TEXT := app.normalize_medical_record_code(p_sjh);
    resolved_id BIGINT;
BEGIN
    IF normalized_sjh IS NOT NULL THEN
        SELECT id
        INTO resolved_id
        FROM app.mr_archive
        WHERE sjh = normalized_sjh;

        IF resolved_id IS NULL AND p_create_when_sjh_present THEN
            INSERT INTO app.mr_archive AS target (sjh, bah)
            VALUES (normalized_sjh, normalized_bah)
            ON CONFLICT (sjh) WHERE sjh IS NOT NULL DO UPDATE
            SET
                bah = COALESCE(target.bah, EXCLUDED.bah),
                updated_at = CURRENT_TIMESTAMP
            RETURNING id INTO resolved_id;
        END IF;

        RETURN resolved_id;
    END IF;

    IF normalized_bah IS NULL THEN
        RETURN NULL;
    END IF;

    -- 缺少上架号时，仅在病案号只对应一条主记录时自动关联，避免错误合并。
    SELECT MIN(id)
    INTO resolved_id
    FROM app.mr_archive
    WHERE bah = normalized_bah
    HAVING COUNT(*) = 1;

    RETURN resolved_id;
END;
$$;

COMMENT ON FUNCTION app.resolve_archive_id(TEXT, TEXT, BOOLEAN)
    IS '按上架号优先解析病案主键；缺少上架号时仅接受唯一病案号匹配';

CREATE OR REPLACE FUNCTION app.sync_archive_from_statistics()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    resolved_id BIGINT;
BEGIN
    NEW.bah := app.normalize_medical_record_code(NEW.bah);
    NEW.sjh := app.normalize_medical_record_code(NEW.sjh);

    IF NEW.archive_id IS NOT NULL THEN
        resolved_id := NEW.archive_id;
    ELSIF NEW.sjh IS NOT NULL THEN
        resolved_id := app.resolve_archive_id(NEW.bah, NEW.sjh, TRUE);
    ELSIF TG_OP = 'UPDATE' AND OLD.archive_id IS NOT NULL THEN
        resolved_id := OLD.archive_id;
    ELSE
        INSERT INTO app.mr_archive AS target (
            bah,
            patient_id,
            patient_name,
            inpatient_department,
            device_id,
            operator_no,
            archive_date,
            discharge_date,
            archive_type,
            page_count,
            source_statistics_id
        )
        VALUES (
            NEW.bah,
            NULLIF(BTRIM(NEW.patientid), ''),
            NULLIF(BTRIM(NEW.patientname), ''),
            NULLIF(BTRIM(NEW.inpatientdepartment), ''),
            NULLIF(BTRIM(NEW.cid), ''),
            NULLIF(BTRIM(NEW.openerno), ''),
            app.try_parse_date(NEW.date),
            app.try_parse_date(NEW.dischargedate),
            NULLIF(BTRIM(NEW.type), ''),
            NEW.pages,
            NEW.id
        )
        ON CONFLICT (source_statistics_id) DO UPDATE
        SET updated_at = CURRENT_TIMESTAMP
        RETURNING id INTO resolved_id;
    END IF;

    UPDATE app.mr_archive
    SET
        sjh = COALESCE(NEW.sjh, sjh),
        bah = COALESCE(NEW.bah, bah),
        patient_id = COALESCE(NULLIF(BTRIM(NEW.patientid), ''), patient_id),
        patient_name = COALESCE(NULLIF(BTRIM(NEW.patientname), ''), patient_name),
        inpatient_department = COALESCE(NULLIF(BTRIM(NEW.inpatientdepartment), ''), inpatient_department),
        device_id = COALESCE(NULLIF(BTRIM(NEW.cid), ''), device_id),
        operator_no = COALESCE(NULLIF(BTRIM(NEW.openerno), ''), operator_no),
        archive_date = COALESCE(app.try_parse_date(NEW.date), archive_date),
        discharge_date = COALESCE(app.try_parse_date(NEW.dischargedate), discharge_date),
        archive_type = COALESCE(NULLIF(BTRIM(NEW.type), ''), archive_type),
        page_count = COALESCE(NEW.pages, page_count),
        updated_at = CURRENT_TIMESTAMP
    WHERE id = resolved_id;

    NEW.archive_id := resolved_id;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mr_statistics_sync_archive ON app.mr_statistics;
CREATE TRIGGER trg_mr_statistics_sync_archive
BEFORE INSERT OR UPDATE OF bah, sjh, patientid, patientname, inpatientdepartment,
    cid, openerno, date, dischargedate, type, pages, archive_id
ON app.mr_statistics
FOR EACH ROW
EXECUTE FUNCTION app.sync_archive_from_statistics();

CREATE OR REPLACE FUNCTION app.resolve_scan_archive_reference()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.bah := app.normalize_medical_record_code(NEW.bah);
    NEW.sjh := app.normalize_medical_record_code(NEW.sjh);

    IF NEW.archive_id IS NULL THEN
        NEW.archive_id := app.resolve_archive_id(NEW.bah, NEW.sjh, NEW.sjh IS NOT NULL);
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_mr_scan_resolve_archive ON app.mr_scan;
CREATE TRIGGER trg_mr_scan_resolve_archive
BEFORE INSERT OR UPDATE OF bah, sjh, archive_id
ON app.mr_scan
FOR EACH ROW
EXECUTE FUNCTION app.resolve_scan_archive_reference();

CREATE OR REPLACE FUNCTION app.resolve_box_archive_reference()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.bah := app.normalize_medical_record_code(NEW.bah);
    NEW.sjh := app.normalize_medical_record_code(NEW.sjh);

    IF NEW.archive_id IS NULL THEN
        NEW.archive_id := app.resolve_archive_id(NEW.bah, NEW.sjh, NEW.sjh IS NOT NULL);
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_archive_box_resolve_archive ON app.mr_archive_box_record;
CREATE TRIGGER trg_archive_box_resolve_archive
BEFORE INSERT OR UPDATE OF bah, sjh, archive_id
ON app.mr_archive_box_record
FOR EACH ROW
EXECUTE FUNCTION app.resolve_box_archive_reference();

-- 装箱表规模较小，可以直接回填。
UPDATE app.mr_archive_box_record b
SET archive_id = app.resolve_archive_id(b.bah, b.sjh, b.sjh IS NOT NULL)
WHERE b.archive_id IS NULL;

-- 扫描表可能达到数千万行，不在 Flyway 事务内一次性更新。
-- 运维端按 last_id 游标循环调用，直到 scanned_count = 0。
CREATE OR REPLACE FUNCTION app.backfill_scan_archive_ids(
    p_after_id INTEGER DEFAULT 0,
    p_batch_size INTEGER DEFAULT 10000
)
RETURNS TABLE(last_id INTEGER, scanned_count INTEGER, updated_count INTEGER)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_batch_size < 1 OR p_batch_size > 100000 THEN
        RAISE EXCEPTION 'p_batch_size must be between 1 and 100000';
    END IF;

    RETURN QUERY
    WITH batch AS (
        SELECT s.id, s.bah, s.sjh
        FROM app.mr_scan s
        WHERE s.id > p_after_id
        ORDER BY s.id
        LIMIT p_batch_size
    ),
    resolved AS (
        SELECT
            b.id,
            app.resolve_archive_id(b.bah, b.sjh, FALSE) AS archive_id
        FROM batch b
    ),
    updated AS (
        UPDATE app.mr_scan s
        SET archive_id = r.archive_id
        FROM resolved r
        WHERE s.id = r.id
          AND s.archive_id IS NULL
          AND r.archive_id IS NOT NULL
        RETURNING s.id
    )
    SELECT
        COALESCE((SELECT MAX(b.id) FROM batch b), p_after_id),
        (SELECT COUNT(*)::INTEGER FROM batch),
        (SELECT COUNT(*)::INTEGER FROM updated);
END;
$$;

COMMENT ON FUNCTION app.backfill_scan_archive_ids(INTEGER, INTEGER)
    IS '按主键游标分批回填 mr_scan.archive_id，避免数千万行一次性更新';

CREATE INDEX IF NOT EXISTS idx_mr_statistics_archive_id
    ON app.mr_statistics (archive_id);

CREATE INDEX IF NOT EXISTS idx_mr_scan_archive_pages
    ON app.mr_scan (archive_id, pages, id)
    WHERE archive_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_archive_box_record_archive_id
    ON app.mr_archive_box_record (archive_id)
    WHERE archive_id IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_mr_statistics_archive'
          AND conrelid = 'app.mr_statistics'::regclass
    ) THEN
        ALTER TABLE app.mr_statistics
            ADD CONSTRAINT fk_mr_statistics_archive
            FOREIGN KEY (archive_id) REFERENCES app.mr_archive(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_mr_scan_archive'
          AND conrelid = 'app.mr_scan'::regclass
    ) THEN
        ALTER TABLE app.mr_scan
            ADD CONSTRAINT fk_mr_scan_archive
            FOREIGN KEY (archive_id) REFERENCES app.mr_archive(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_archive_box_record_archive'
          AND conrelid = 'app.mr_archive_box_record'::regclass
    ) THEN
        ALTER TABLE app.mr_archive_box_record
            ADD CONSTRAINT fk_archive_box_record_archive
            FOREIGN KEY (archive_id) REFERENCES app.mr_archive(id)
            ON DELETE SET NULL NOT VALID;
    END IF;
END;
$$;

CREATE OR REPLACE VIEW app.v_archive_summary AS
SELECT
    a.id,
    a.sjh,
    a.bah,
    a.patient_id,
    a.patient_name,
    a.inpatient_department,
    a.archive_date,
    a.discharge_date,
    a.archive_type,
    a.page_count,
    COUNT(s.id) AS scan_count,
    COALESCE(SUM(s.pages), 0) AS scan_page_count,
    a.created_at,
    a.updated_at
FROM app.mr_archive a
LEFT JOIN app.mr_scan s ON s.archive_id = a.id AND s.uploadflag <> 0
GROUP BY a.id;

COMMENT ON VIEW app.v_archive_summary IS '病案主数据与已关联影像数量汇总';
