-- 结构化运行错误中心：按指纹聚合同类 WARN/ERROR，并与接口 Request ID 关联。
CREATE TABLE IF NOT EXISTS app.system_error_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_id VARCHAR(32) NOT NULL UNIQUE,
    error_ids VARCHAR(32)[] NOT NULL DEFAULT ARRAY[]::VARCHAR(32)[],
    fingerprint VARCHAR(64) NOT NULL UNIQUE,
    level VARCHAR(16) NOT NULL,
    module VARCHAR(128),
    logger_name VARCHAR(512) NOT NULL,
    exception_type VARCHAR(512),
    message_summary TEXT NOT NULL,
    stack_trace TEXT,
    request_id VARCHAR(64),
    thread_name VARCHAR(256),
    first_seen_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    occurrence_count BIGINT NOT NULL DEFAULT 1,
    status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
    acknowledged_by VARCHAR(128),
    resolved_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT chk_system_error_event_status CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')),
    CONSTRAINT chk_system_error_event_level CHECK (level IN ('WARN', 'ERROR')),
    CONSTRAINT chk_system_error_event_occurrence_count CHECK (occurrence_count > 0)
);

COMMENT ON TABLE app.system_error_event IS '后端 WARN/ERROR 聚合事件，仅保存脱敏摘要与受控堆栈';
COMMENT ON COLUMN app.system_error_event.error_id IS '错误组首次编号，作为页面展示的稳定编号';
COMMENT ON COLUMN app.system_error_event.error_ids IS '同一错误组最近 50 次发生时返回的错误编号，可用于用户报障检索';
COMMENT ON COLUMN app.system_error_event.fingerprint IS '按日志级别、记录器、异常类型和规范化消息生成的 SHA-256';
COMMENT ON COLUMN app.system_error_event.request_id IS '可与 access_log.request_id 关联的最近一次请求编号';

CREATE INDEX IF NOT EXISTS idx_system_error_event_last_seen
    ON app.system_error_event (last_seen_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_system_error_event_status_last_seen
    ON app.system_error_event (status, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_error_event_level_last_seen
    ON app.system_error_event (level, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_error_event_request_id
    ON app.system_error_event (request_id) WHERE request_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_system_error_event_error_ids
    ON app.system_error_event USING GIN (error_ids);

-- 新权限保持独立；system:manage 继续作为上级权限，由后端权限解析器继承。
UPDATE app.mr_auth_role
SET permissions = CONCAT_WS(',', NULLIF(TRIM(permissions), ''), 'system:error:read')
WHERE (code = 'ADMIN' OR permissions LIKE '%system:read%' OR permissions LIKE '%system:manage%' OR permissions LIKE '%log:read%')
  AND NOT ('system:error:read' = ANY(STRING_TO_ARRAY(REPLACE(COALESCE(permissions, ''), ' ', ''), ',')));

UPDATE app.mr_auth_role
SET permissions = CONCAT_WS(',', NULLIF(TRIM(permissions), ''), 'system:error:manage')
WHERE (code = 'ADMIN' OR permissions LIKE '%system:manage%')
  AND NOT ('system:error:manage' = ANY(STRING_TO_ARRAY(REPLACE(COALESCE(permissions, ''), ' ', ''), ',')));
