-- ============================================================
-- 影像档案袋智能分类第一阶段
-- 1. 独立保存 OCR/规则建议，不直接覆盖 mr_scan.btype；
-- 2. 支持按病案异步执行识别任务；
-- 3. 人工确认和手工改类均保留审计记录。
-- ============================================================

CREATE TABLE IF NOT EXISTS app.mr_record_type_dict (
    btype               SMALLINT PRIMARY KEY,
    type_code           VARCHAR(64) NOT NULL UNIQUE,
    type_name           VARCHAR(100) NOT NULL,
    keywords            TEXT NOT NULL DEFAULT '',
    negative_keywords   TEXT NOT NULL DEFAULT '',
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order          INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_mr_record_type_btype CHECK (btype BETWEEN 0 AND 99)
);

COMMENT ON TABLE app.mr_record_type_dict IS '病案影像类型字典及第一阶段 OCR 关键词规则';
COMMENT ON COLUMN app.mr_record_type_dict.keywords IS '以 | 分隔的正向关键词，优先匹配页面标题区域';
COMMENT ON COLUMN app.mr_record_type_dict.negative_keywords IS '以 | 分隔的排除关键词';

INSERT INTO app.mr_record_type_dict (
    btype, type_code, type_name, keywords, negative_keywords, enabled, sort_order
) VALUES
    (0,  'unclassified',     '未分类',     '',                                                       '', FALSE, 0),
    (1,  'record_home',      '病案首页',   '住院病案首页|病案首页|病历首页',                         '', TRUE, 10),
    (2,  'progress_note',    '病程记录',   '首次病程记录|日常病程记录|病程记录|抢救记录|转科记录',   '术后首次病程记录', TRUE, 20),
    (3,  'operation_note',   '手术记录',   '手术记录|手术安全核查表|手术风险评估表|麻醉记录',       '术后首次病程记录', TRUE, 30),
    (4,  'postoperative',    '术后病程',   '术后首次病程记录|术后病程记录',                         '', TRUE, 40),
    (5,  'nursing_note',     '护理记录',   '护理记录单|护理评估单|入院护理评估|护理计划',           '', TRUE, 50),
    (6,  'consultation',     '会诊单',     '会诊记录|会诊申请单|会诊意见',                         '', TRUE, 60),
    (7,  'special_exam',     '特殊检查',   'CT报告|磁共振报告|MRI报告|超声检查报告|心电图报告|内镜检查报告|病理报告', '', TRUE, 70),
    (8,  'laboratory',       '检验单',     '检验报告|检验结果|血常规|尿常规|生化检验|免疫检验|微生物检验', '', TRUE, 80),
    (9,  'medical_order',    '医嘱',       '长期医嘱|临时医嘱|医嘱单|医嘱记录',                   '', TRUE, 90),
    (10, 'temperature',      '体温单',     '体温单|体温记录单',                                   '', TRUE, 100),
    (12, 'discharge_record', '出院记录',   '出院记录|出院小结|死亡记录|死亡小结',                   '', TRUE, 120),
    (13, 'admission_record', '大病历',     '入院记录|住院志|入院病历|大病历',                       '', TRUE, 130),
    (14, 'other',            '其它',       '',                                                       '', TRUE, 140)
ON CONFLICT (btype) DO UPDATE SET
    type_code = EXCLUDED.type_code,
    type_name = EXCLUDED.type_name,
    keywords = EXCLUDED.keywords,
    negative_keywords = EXCLUDED.negative_keywords,
    enabled = EXCLUDED.enabled,
    sort_order = EXCLUDED.sort_order,
    updated_at = CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS app.mr_classification_job (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id          BIGINT NOT NULL REFERENCES app.mr_archive(id) ON DELETE CASCADE,
    scope_type          VARCHAR(24) NOT NULL DEFAULT 'UNCLASSIFIED',
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    total_count         BIGINT NOT NULL DEFAULT 0,
    processed_count     BIGINT NOT NULL DEFAULT 0,
    suggested_count     BIGINT NOT NULL DEFAULT 0,
    no_match_count      BIGINT NOT NULL DEFAULT 0,
    failed_count        BIGINT NOT NULL DEFAULT 0,
    cursor_scan_id      INTEGER,
    model_version       VARCHAR(64),
    error_message       TEXT,
    created_by          VARCHAR(64),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_classification_job_scope CHECK (scope_type IN ('UNCLASSIFIED', 'LOW_CONFIDENCE', 'ALL')),
    CONSTRAINT chk_classification_job_status CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS app.mr_image_classification (
    scan_id              INTEGER PRIMARY KEY REFERENCES app.mr_scan(id) ON DELETE CASCADE,
    archive_id           BIGINT NOT NULL REFERENCES app.mr_archive(id) ON DELETE CASCADE,
    predicted_btype      SMALLINT REFERENCES app.mr_record_type_dict(btype),
    confidence           NUMERIC(6,5),
    classification_state VARCHAR(24) NOT NULL DEFAULT 'UNPROCESSED',
    effective_source     VARCHAR(32),
    model_version        VARCHAR(64),
    rule_version         VARCHAR(64),
    ocr_title            TEXT,
    evidence             JSONB NOT NULL DEFAULT '{}'::JSONB,
    image_checksum       VARCHAR(32),
    reviewed_btype       SMALLINT REFERENCES app.mr_record_type_dict(btype),
    reviewed_by          VARCHAR(64),
    reviewed_at          TIMESTAMPTZ,
    error_message        TEXT,
    classified_at        TIMESTAMPTZ,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_image_classification_confidence CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CONSTRAINT chk_image_classification_state CHECK (
        classification_state IN ('UNPROCESSED', 'PROCESSING', 'SUGGESTED', 'NO_MATCH', 'CONFIRMED', 'REJECTED', 'FAILED')
    )
);

CREATE TABLE IF NOT EXISTS app.mr_image_type_audit (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id             INTEGER NOT NULL REFERENCES app.mr_scan(id) ON DELETE CASCADE,
    archive_id          BIGINT REFERENCES app.mr_archive(id) ON DELETE SET NULL,
    previous_btype      SMALLINT,
    proposed_btype      SMALLINT,
    final_btype         SMALLINT,
    action              VARCHAR(32) NOT NULL,
    source              VARCHAR(32) NOT NULL,
    model_version       VARCHAR(64),
    confidence          NUMERIC(6,5),
    operated_by         VARCHAR(64),
    reason              TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_classification_job_archive_created
    ON app.mr_classification_job (archive_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_classification_job_status
    ON app.mr_classification_job (status, created_at);
CREATE INDEX IF NOT EXISTS idx_image_classification_archive_state
    ON app.mr_image_classification (archive_id, classification_state);
CREATE INDEX IF NOT EXISTS idx_image_classification_confidence
    ON app.mr_image_classification (confidence)
    WHERE classification_state = 'SUGGESTED';
CREATE INDEX IF NOT EXISTS idx_image_type_audit_scan_created
    ON app.mr_image_type_audit (scan_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_image_type_audit_archive_created
    ON app.mr_image_type_audit (archive_id, created_at DESC);
