-- 运维诊断中心：权限矩阵版本、导出下载统计。

ALTER TABLE app.archive_export_job
    ADD COLUMN IF NOT EXISTS download_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_downloaded_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_archive_export_job_status_created_at
    ON app.archive_export_job(status, created_at DESC);

CREATE TABLE IF NOT EXISTS app.permission_matrix_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version VARCHAR(128) NOT NULL,
    matrix_json JSONB NOT NULL,
    created_by VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_permission_matrix_snapshot_version
    ON app.permission_matrix_snapshot(version);

COMMENT ON TABLE app.permission_matrix_snapshot
    IS '权限矩阵版本快照，用于比较角色、接口和操作权限变化';
COMMENT ON COLUMN app.archive_export_job.download_count
    IS '导出文件下载请求次数，包括 Range 续传请求';
COMMENT ON COLUMN app.archive_export_job.last_downloaded_at
    IS '最近一次下载或续传请求时间';
