-- 外部系统安全访问影像档案袋。
-- 仅保存随机票据与会话令牌的 SHA-256 摘要，不保存令牌明文。

CREATE TABLE IF NOT EXISTS app.mr_external_archive_nonce (
    client_id   VARCHAR(64) NOT NULL,
    nonce_hash  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_external_archive_nonce PRIMARY KEY (client_id, nonce_hash)
);

CREATE TABLE IF NOT EXISTS app.mr_external_archive_ticket (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_hash       VARCHAR(64) NOT NULL UNIQUE,
    client_id         VARCHAR(64) NOT NULL,
    external_user_id  VARCHAR(128) NOT NULL,
    allow_download    BOOLEAN NOT NULL DEFAULT FALSE,
    grant_json        JSONB NOT NULL,
    expires_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    used_at           TIMESTAMP WITHOUT TIME ZONE,
    created_ip        VARCHAR(64),
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app.mr_external_archive_session (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_hash      VARCHAR(64) NOT NULL UNIQUE,
    client_id         VARCHAR(64) NOT NULL,
    external_user_id  VARCHAR(128) NOT NULL,
    allow_download    BOOLEAN NOT NULL DEFAULT FALSE,
    grant_json        JSONB NOT NULL,
    expires_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked_at        TIMESTAMP WITHOUT TIME ZONE,
    created_ip        VARCHAR(64),
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    last_access_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app.mr_external_archive_access_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id         VARCHAR(64) NOT NULL,
    external_user_id  VARCHAR(128),
    bah               VARCHAR(32),
    sjh               VARCHAR(32),
    action            VARCHAR(64) NOT NULL,
    image_id          INTEGER,
    client_ip         VARCHAR(64),
    user_agent        TEXT,
    result            VARCHAR(20) NOT NULL,
    request_id        VARCHAR(128),
    detail            VARCHAR(500),
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_external_archive_ticket_expiry
    ON app.mr_external_archive_ticket (expires_at)
    WHERE used_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_external_archive_session_expiry
    ON app.mr_external_archive_session (expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_external_archive_access_client_time
    ON app.mr_external_archive_access_log (client_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_external_archive_access_target_time
    ON app.mr_external_archive_access_log (bah, sjh, created_at DESC);

COMMENT ON TABLE app.mr_external_archive_ticket IS '外部系统一次性影像访问票据，仅保存令牌摘要';
COMMENT ON TABLE app.mr_external_archive_session IS '外部影像档案袋短期只读会话，仅保存令牌摘要';
COMMENT ON TABLE app.mr_external_archive_access_log IS '外部影像档案袋访问审计日志';
