/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/Admin.vue')['default']
    AdminDashboard: typeof import('./src/components/AdminDashboard.vue')['default']
    DashboardView: typeof import('./src/components/admin/DashboardView.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GsapCounter: typeof import('./src/components/shared/GsapCounter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IdCardTest: typeof import('./src/components/IdCardTest.vue')['default']
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    ImageGalleryAdmin: typeof import('./src/components/ImageGalleryAdmin.vue')['default']
    ImageGalleryEl: typeof import('./src/components/ImageGalleryEl.vue')['default']
    ImageGalleryEl2: typeof import('./src/components/ImageGalleryEl-2.vue')['default']
    ImageGalleryEl3: typeof import('./src/components/ImageGalleryEl-3.vue')['default']
    LogCleanupTestView: typeof import('./src/components/admin/LogCleanupTestView.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    LogsView: typeof import('./src/components/admin/LogsView.vue')['default']
    MessageToast: typeof import('./src/components/MessageToast.vue')['default']
    MessageToastDemo: typeof import('./src/components/MessageToastDemo.vue')['default']
    MonitoringView: typeof import('./src/components/admin/MonitoringView.vue')['default']
    PasswordCipherView: typeof import('./src/components/admin/PasswordCipherView.vue')['default']
    PermissionsView: typeof import('./src/components/admin/PermissionsView.vue')['default']
    PressureTestView: typeof import('./src/components/admin/PressureTestView.vue')['default']
    PrintPage: typeof import('./src/components/PrintPage.vue')['default']
    RecordsStatisticsView: typeof import('./src/components/admin/RecordsStatisticsView.vue')['default']
    RecordsView: typeof import('./src/components/admin/RecordsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./src/components/admin/SettingsView.vue')['default']
    StatisticsDetailView: typeof import('./src/components/admin/StatisticsDetailView.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    TestingView: typeof import('./src/components/admin/TestingView.vue')['default']
    UsersView: typeof import('./src/components/admin/UsersView.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
